# Generated by Django 5.2.4 on 2025-07-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
