# Generated by Django 5.2.4 on 2025-07-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='if you can see this, Fuck you'),
            preserve_default=False,
        ),
    ]
