# Generated by Django 5.2.4 on 2025-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('None', 'None'), ('Middle School', 'Middle School'), ('High School', 'High School'), ('College', 'College')], default='None', max_length=20),
        ),
    ]
