# Generated by Django 5.2.4 on 2025-07-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
